apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-apps
  namespace: rancher-app-dev
  labels:
    app: rancher-apps
    env: dev

spec:
  replicas: 3
  selector:
    matchLabels:
      app: rancher-apps

  template:
    metadata:
      labels:
        app: rancher-apps

    spec:
      containers:
        - name: rancher-apps
          image: 44.202.77.70:30002/rancher/myapp:BUILD_NUMBER
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"

            limits:
              cpu: "300m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: rancher-apps-service
  namespace: rancher-app-dev

spec:
  type: NodePort

  selector:
    app: rancher-apps

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31080

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rancher-apps-hpa
  namespace: rancher-app-dev

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rancher-apps

  minReplicas: 3
  maxReplicas: 10

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70